//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by multifxVST.rc
//
#define IDD_Chain                       101
#define IDB_BITMAP1                     102
#define IDD_DIALOG1                     103
#define IDB_HOVERBUTTON                 104
#define IDB_COLUMNHEADER_END            105
#define IDB_COLUMNHEADER_SPAN           106
#define IDB_COLUMNHEADER_START          107
#define IDB_HORIZONTAL_SCROLLBAR_LEFTARROW 108
#define IDB_HORIZONTAL_SCROLLBAR_RIGHTARROW 109
#define IDB_HORIZONTAL_SCROLLBAR_SPAN   110
#define IDB_HORIZONTAL_SCROLLBAR_THUMB  111
#define IDB_VERTICLE_SCROLLBAR_BOTTOM   112
#define IDD_PARMS                       113
#define IDB_VERTICLE_SCROLLBAR_DOWNARROW 114
#define IDB_VERTICLE_SCROLLBAR_SPAN     115
#define IDB_VERTICLE_SCROLLBAR_THUMB    116
#define IDB_VERTICLE_SCROLLBAR_TOP      117
#define IDB_VERTICLE_SCROLLBAR_UPARROW  118
#define IDB_CBN                         119
#define IDB_CBH                         120
#define IDB_CBBAR                       121
#define IDR_MENU1                       122
#define IDR_MNUVST                      123
#define IDD_CONTROLER                   124
#define IDD_DIALOG2                     125
#define IDD_MAIN                        126
#define IDB_BITMAP2                     127
#define IDB_BITMAP16                    128
#define IDM_VSTMNU                      130
#define IDR_MNUEFFECTS                  131
#define IDB_WINDOWS_BUTTON              132
#define IDB_MAIN                        133
#define IDB_BYPASS                      134
#define IDB_PRESET                      135
#define IDB_RIGHT_ARROW_EFFECT          136
#define IDB_BITMAP4                     137
#define IDB_LEFT_ARROW_EFFECT           137
#define IDC_CURSOR_HAND                 140
#define IDC_LSTPLUG                     141
#define IDC_BTNUP                       142
#define IDC_BTNDOWN                     143
#define IDC_BTNE                        144
#define IDC_BTNE2                       145
#define IDC_BTNADD                      146
#define IDC_BTNSUPPR                    147
#define IDC_SLDCHAINE                   148
#define IDC_EDIT1                       149
#define IDC_SLDCHAINE2                  150
#define IDC_TXTCONTROLEUR_NOTE          151
#define IDC_TXTCHAINE                   152
#define IDC_BTNCOPIETO                  153
#define IDC_TXTINCREMENT                154
#define IDC_BTNSAVE                     155
#define IDC_BUTTON2                     156
#define IDC_BTNLOAD                     157
#define IDC_BTNSAVE3                    158
#define IDC_BTNSAVE2                    159
#define IDC_BTNLOAD2                    160
#define IDC_LISTVST                     161
#define IDC_TXTCHAINE2                  162
#define IDC_LSTCONTROLER                163
#define IDC_BTNCLRCHAIN                 164
#define IDC_BUTTON1                     165
#define IDC_BTNPASTETO                  166
#define IDC_BUTTON3                     167
#define IDC_BUTTON4                     168
#define IDC_BTNCHMOINS                  169
#define IDC_COMBO1                      170
#define IDC_CBCHANNEL                   171
#define IDC_BUTTON7                     172
#define IDC_BTNEFFECTTXT                173
#define IDC_BTNEFFUP                    174
#define IDC_BTNEFFDOWN                  175
#define IDC_TXTEFF                      176
#define IDC_BUTTON5                     177
#define IDC_BTNCHPLUS                   178
#define IDC_TXTUSED                     179
#define IDC_BTNEFFECTTXT2               179
#define IDC_BUTTON6                     180
#define IDC_BTNBYPASS                   181
#define IDC_TXTCOPIED                   182
#define IDC_BTNVALIDATE                 183
#define IDC_CBACTION                    184
#define IDC_BTNLOADMIDI                 185
#define IDC_CKSIMPLE                    186
#define IDC_LISTPARMS                   187
#define IDC_BTNLOADMIDI2                188
#define IDC_CBNOTE                      189
#define IDC_TXTDESC1                    190
#define IDC_TXTDESC3                    191
#define IDC_TXTINFOCTAF                 192
#define IDC_CB_CONTROLEUR               193
#define IDC_SCROLLBAR1                  194
#define IDC_STATIC1                     195
#define IDC_STATIC2                     196
#define IDC_STATIC3                     197
#define IDC_DESC2                       198
#define IDC_PARMLIST                    199
#define IDC_PARMVAL                     200
#define IDC_PARMTEXT                    201
#define IDC_RVALUE                      202
#define IDM_EFF_PROGRAM_0               1029
#define ID_PLUG_PROGRAMS                32771
#define ID_PLUG_FXB                     32772
#define ID_FXB_SAVEBANK                 32773
#define ID_FXB_LOADBANK                 32774
#define ID_FXB_LOADFXP                  32775
#define ID_FXB_SAVEFXP                  32776
#define ID_PLUG_PRESET                  32777
#define ID_PRESET_ENREGISTRER           32778
#define ID_PRESET_SUPPRIMER             32779
#define ID_EFFECTS_BROWSE               32780
#define ID_EFFECTS_                     32781
#define ID_Menu                         32782
#define ID_EFFECTS_FUTURLISTEDESEFFETS  32783
#define ID_EFFECTS_SHELLPLUG            32784

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        138
#define _APS_NEXT_COMMAND_VALUE         32785
#define _APS_NEXT_CONTROL_VALUE         204
#define _APS_NEXT_SYMED_VALUE           303
#endif
#endif
